name: pytorch
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python
  - jupyter
  - numpy
  - pip
  - pip:
      # install torch as pip dependency to ensure platform specific version is installed
      - torch